export default {
    lang: "en",
    hints: {
        apartmentDetails: "Example: separate bathroom, kitchen with an area of 8m2, two balconies, no elevator, closed courtyard.",
        description: "Example for rent: possible with small pets, there is a washing machine. Example for sale: possible sale under the e-Oselya program.",
        contact: "Enter your contact details (phone or email).",
        price: "Enter the monthly rent or the property price.",
        location: "Specify the location of the property and verify that the address exists.",
    },
    header:[
        {id:"0",text:"My Dream House"},
        {id:"1",text:"Place an ad"},
        {id:"2",text:"Select option"},
        {id:"3",text:"For sale"},
        {id:"4",text:"For rent"},
        {id:"5",text:"About"},
        {id:"6",text:"My profile"},
        {id:"7",text:"Edit my Listings"},
        {id:"8",text:"Edit my Comments"},
        {id:"9",text:"LogOut"},
        {id:"10",text:"Logging out will remove your account data and all your sale or rental listings from our platform."},
        {id:"11",text:"Agents"},
        {id:"12",text:"Edit my Notification"},
        {id:"13",text:"Services"},
        {id:"14",text:"Home" }
    ],
    offers:[
        {id:"0",text:"Find Your Dream Home"},
        {id:"1",text:"Explore the best properties for sale and rent."},
        {id:"2",text:"Show all lists"},
        {id:"3",text:"Filters"},
        {id:"4",text:"Please select a type of offer"},
        {id:"5",text:"For rent"},
        {id:"6",text:"For sale"},
        {id:"7",text:"Please select a type of property"},
        {id:"8",text:"Apartment"},
        {id:"9",text:"Private house"},
        {id:"10",text:"Commercial real estate"},
        {id:"11",text:"Please select a range of acceptable prices"},
        {id:"12",text:"Sort lists by posting date"},
        {id:"13",text:"From new to old"},
        {id:"14",text:"From old to new"},
        {id:"15",text:"Search"},
        {id:"16",text:"Reset Filters"},
        {id:"17",text:"Select the location you are looking for"},
        {id:"18",text:"Enter the location you are looking for ..."},
        {id:"19",text:"Select search range"},
        {id:"20",text:"Length: "},
        {id:"21",text:"🔍 Need help using the map filter?"},
        {id:"22",text:"1. Enter a location in the “Destination” field — for example, “Kyiv” or “Warsaw”."},
        {id:"23",text:"2. Choose a distance in kilometers (Range) to limit how far from that location listings can appear."},
        {id:"24",text:"3. You can also filter by Listing Type (e.g., rent, sale) and Property Type (e.g., apartment, house)."},
        {id:"25",text:"4. Press “Search” to update the map and show only the listings that match your criteria."},
        {id:"26",text:"5. If no results appear:"},
        {id:"27",text:"– Make sure the location exists and is spelled correctly."},
        {id:"28",text:"– Try increasing the distance."},
        {id:"29",text:"– Try resetting filters with the “Reset Filter” button to show all listings again."},
        {id:"30",text:"🟦 The blue circle shows your selected area. Only listings inside that circle are displayed."},
        {id:"31",text:"Collapse map"},
        {id:"32",text:"To place your Advertisement,"},
        {id:"33",text:"Register to Post an Advertisement"},
        {id:"34",text:"fill out the form with your property details."},
        {id:"35",text:"Your offer will reach the right audience right away."},
        {id:"36",text:"Sign Up"},
        {id:"37",text:"Log In"},
        {id:"38",text:"Popular Listings"},
        {id:"39",text:"Advertising from our partners"},
        {id:"40",text:"Sign In or Register to Post an Advertisement"},
        {id:"41",text:"Your services can be advertised here"},
        {id:"42",text:"Loading video…"},
        {id:"43",text:"Current listings from owners and agencies across the country"},
    ],
    cards:[
        {id:"0",text:"Property : "},
        {id:"1",text:"Description of property : "},
        {id:"2",text:"Monthly rental property : "},
        {id:"3",text:"Selling price : "},
        {id:"4",text:"Owner's contact data : "},
        {id:"5",text:"Location : "},
        {id:"6",text:"Property type : "},
        {id:"7",text:"Time of download : "},
        {id:"8",text:"For sale"},
        {id:"9",text:"For rent"},
        {id:"10",text:"For rent"},
        {id:"11",text:"For sale"},
        {id:"12",text:"Apartment"},
        {id:"13",text:"Private house"},
        {id:"14",text:"Commercial"},
        {id:"15",text:"rooms"},
        {id:"16",text:"m²"},
        {id:"17",text:"/ mo."},
        {id:"18",text:"New build"},
        {id:"19",text:"View details"},
        {id:"20",text:"of"},
        {id:"21",text:"fl."},
        {id:"22",text:"No photo"},
    ],
    details:[
        {id:"0",text:"Loading..."},
        {id:"1",text:"Listings not found"},
        {id:"2",text:"Features of the property: "},
        {id:"3",text:"Date of publication : "},
        {id:"4",text:"Back to Listings"},
        {id:"5",text:"Delete user: "},
        {id:"6",text:"Hide feedback"},
        {id:"7",text:"Leave feedback"},
        {id:"8",text:"Reviews for this advertisement"},
        {id:"9",text:"COMMENTS"},
        {id:"10",text:"Leave a comment"},
        {id:"11",text:"review published: "},
        {id:"12",text:"ad number: "},
        {id:"13",text:"Type of Property: "},
        {id:"14",text:"Apartment"},
        {id:"15",text:"Private house"},
        {id:"16",text:"Commercial real estate"},
        {id:"17",text:"numbers of rooms"},
        {id:"18",text:"total area: ",measur:" m2"},
        {id:"19",text:"floor/floors in the building:"},
        {id:"20",text:"preferences: "},
        {id:"21",text:"monthly rental cost:"},
        {id:"22",text:"cost: "},
        {id:"23",text:"contacts: "},
        {id:"24",text:"new building"},
        {id:"25",text:"secondary housing"},
        {id:"26",text:"Enter a comment..."},
        {id:"27",text:"Owner: "},
        {id:"28",text:"Chat with owner"},
        {id:"29",text:"Sign in or register to leave a review"},
    ],
    imageUploader:[
        {id:"0",text:"Drag & drop image"},
        {id:"1",text:"or click to browse"},
        {id:"2",text:"Tap to upload a photo"},
    ],
    login:[
        {id:"0",text:"Sign In"},
        {id:"1",text:"Welcome, "},
        {id:"2",text:"Back to Home"},
        {id:"3",text:"Sign In"},
        {id:"4",text:"Create account"},
        {id:"5",text:"Authorization successful!"},
        {id:"6",text:"Password"},
        {id:"7",text:"Enter your account details"},
        {id:"8",text:"Loading..."},
        {id:"9",text:"Login successful! Redirecting..."},
        {id:"10",text:"Forgot password?"},
        {id:"11",text:"or"},
        {id:"12",text:"no account yet?"},
        {id:"13",text:"No account?"},
        {id:"14",text:"Register"},
        {id:"15",text:"Go to Home"},
        {id:"16",text:"Find Your Dream Home"},
        {id:"17",text:"Thousands of properties. Easy search, detailed descriptions and current prices."},
        {id:"18",text:"Listings"},
        {id:"19",text:"Satisfied clients"},
        {id:"20",text:"Support"},
    ],
    myComments:[
        {id:"0",text:"Comments not found !"},
        {id:"1",text:", select comment to edit"},
        {id:"2",text:" Property : "},
        {id:"3",text:"Description of property : "},
        {id:"4",text:"Monthly rental pay : "},
        {id:"5",text:"Selling price : "},
        {id:"6",text:"Owner's contact data : "},
        {id:"7",text:"Location : "},
        {id:"8",text:"Property type : "},
        {id:"9",text:"Date of download : "},
        {id:"10",text:"For sale"},
        {id:"11",text:"For rent"},
        {id:"12",text:"Enter a comment"},
        {id:"13",text:"Update Comment"},
        {id:"14",text:" Delete Comment"},
        {id:"15",text:"Respected "},
        {id:"16",text:"Listing #"},
        {id:"17",text:"Owner: "},
        {id:"18",text:"Comment author: "},
    ],
    myListings:[
        {id:"0",text:"Select listing to edit "},
        {id:"1",text:""},
        {id:"2",text:" Property : "},
        {id:"3",text:"Description of property : "},
        {id:"4",text:"Monthly rental pay : "},
        {id:"5",text:"Selling price : "},
        {id:"6",text:"Owner's contact data : "},
        {id:"7",text:"Location : "},
        {id:"8",text:"Property type : "},
        {id:"9",text:"Date of download : "},
        {id:"10",text:"For sale"},
        {id:"11",text:"For rent"},
        {id:"12",text:"You don't have any listings yet!"},
        {id:"13",text:"Listing #"},
        {id:"14",text:"Owner: "},
        {id:"15",text:"Edit"},
        {id:"16",text:"Delete Listing"},
    ],
    myNotification:[
        {id:"0",text:"select notification to edit"},
        {id:"1",text:"Requests on notifications not found !"},
        {id:"2",text:"Alert request creation time"},
        {id:"3",text:"Listing type"},
        {id:"4",text:"Property type"},
        {id:"5",text:"Category by construction date"},
        {id:"6",text:"Minimum numbers of room"},
        {id:"7",text:"Maximum numbers of room"},
        {id:"8",text:"Minimum total area"},
        {id:"9",text:"Maximum total area"},
        {id:"10",text:"Minimum floor"},
        {id:"11",text:"Maximum floor"},
        {id:"12",text:"Minimum price"},
        {id:"13",text:"Maximum price"},
        {id:"14",text:"Location sought"},
        {id:"15",text:"Location range"},
        {id:"16",text:"E-mail address"},
        {id:"17",text:"Edit notification"},
        {id:"18",text:"Delete notification"},
        {id:"19",text:"Alert owner: "},
    ],
    notification:[
        {id:"0",text:"Fill out the form with the required property parameters."},
        {id:"1",text:"Please select the required number of rooms."},
        {id:"2",text:"Please select the required total area."},
        {id:"3",text:"Please select the required floor."},
        {id:"4",text:"Please select a range of acceptable prices."},
        {id:"5",text:"Enter location and select search radius."},
        {id:"6",text:"Acceptable distance: "},
        {id:"7",text:"Check address"},
        {id:"8",text:"Collapse a map"},
        {id:"9",text:"Leave your email for notifications"},
        {id:"10",text:"Leave a notification request"},
        {id:"11",text:"Edit notification request"},
        {id:"12",text:"From:"},
        {id:"13",text:"to:"},
        {id:"14",text:"After paying for the service, you will receive a notification to your email address about the publication of the ad you need within 3 months."},
        {id:"15",text:"Property Alert Notifications"},
        {id:"16",text:"Min"},
        {id:"17",text:"Max"},
        {id:"18",text:"Enter address"},
        {id:"19",text:"Please enter a valid address!"},
        {id:"20",text:"Failed to save. Please try again."},
        {id:"21",text:"An error occurred. Please try again later."},
        {id:"22",text:"My Notifications"},
        {id:"23",text:"Back to Home"},
        {id:"24",text:"Listing type"},
        {id:"25",text:"Property type"},
        {id:"26",text:"Building type"},
        {id:"27",text:"Request saved successfully!"},
    ],
    addAgent:[
        {id:"0",text:"Photo of agent:"},
        {id:"1",text:"Full name: "},
        {id:"2",text:"Job title: "},
        {id:"3",text:"Email: "},
        {id:"4",text:"Sale volume: "},
        {id:"5",text:"Total deal: "},
        {id:"6",text:"Rating: "},
        {id:"7",text:"License number: "},
        {id:"8",text:"Phone number: "},
        {id:"9",text:"Save Changes"},
        {id:"10",text:"Add Agent"},
        {id:"11",text:"Delete agent"},
        {id:"12",text:"Back to agents list"},
        {id:"13",text:"Edit mode"},
        {id:"14",text:"Full name"},
        {id:"15",text:"Job title • service area"},
        {id:"16",text:"Email"},
        {id:"17",text:"Sale volume"},
        {id:"18",text:"Total deal"},
        {id:"19",text:"Rating"},
        {id:"20",text:"License number"},
        {id:"21",text:"Phone"},
        {id:"22",text:"Agent's data updated successfully!"},
        {id:"23",text:"Agent's data added successfully."},
        {id:"24",text:"Fill in all fields with the required data"},
        {id:"25",text:"Image deleted!"},
        {id:"26",text:"Error deleting image: "},
        {id:"27",text:"Failed to update agent's data: "},
        {id:"28",text:"Failed to add agent's data: "},
        {id:"29",text:"Failed to delete agent's data: "},
    ],
    agents:[
        {id:"0",text:"Find the most experienced real estate agents in Kharkiv, Ukr"},
        {id:"1",text:"«MyDreamHouse» agents close twice as many deals as other real estate agents. We’re local experts who know how to help you win in today’s market."},
        {id:"2",text:"Sale volume"},
        {id:"3",text:"Total deal"},
        {id:"4",text:"Avg rating"},
        {id:"5",text:"Contact"},
        {id:"6",text:"License plate: # "},
    ],
    listings:{
        editModeTitle:          "Listing editing mode:",
        greeting:               "Dear ",
        editSuffix:             ", please edit the information about your property if necessary.",
        createSuffix:           ", please fill out the form with information about your property for ",
        typeSale:               "sale",
        typeRent:               "rent",
        propertyTypeFlat:       "Apartment",
        propertyTypePrivate:    "Private house",
        propertyTypeCommercial: "Commercial real estate",
        fieldApartmentDetails:  "features of the real estate object",
        fieldDescription:       "requirements or preferences",
        fieldContact:           "contact data",
        fieldPrice:             "price in hryvnias",
        fieldLocation:          "location",
        checkAddress:           "Check address existence",
        showImages:             "Show my images",
        next:                   "Next",
        photoInstruction:       "Fill the slots with 2 to 6 photos of your property",
        saveChanges:            "Save Changes",
        publish:                "Add Listing",
        backToListings:         "Back to my Listings",
        deleteListing:          "Delete Listing",
        clearForm:              "Clean Form",
        goToPublished:          "Go to published listings",
        forRent:                "For rent",
        forSale:                "For sale",
        newBuilding:            "New building",
        secondaryHousing:       "Secondary housing",
        numberOfRooms:          "numbers of rooms",
        totalArea:              "total area",
        floorNumber:            "number of floor",
        totalFloors:            "number of storeys of the building",
        previousStep:           "Go back to previous step",
        fillAllFields:          "All fields must be filled in",
        addressExists:          "This address exists",
        addressNotFound:        "This address does not exist or was entered incorrectly",
        collapseMap:            "collapse map",
        formTitleFor:           "Form for listing about",
    },
    registration:[
        {id:"0",text:"Registration form"},
        {id:"1",text:"Full Name"},
        {id:"2",text:"Email"},
        {id:"3",text:"Password"},
        {id:"4",text:"Preferred Contact"},
        {id:"5",text:"Phone"},
        {id:"6",text:"Telegram"},
        {id:"7",text:"WhatsApp"},
        {id:"8",text:"Viber"},
        {id:"9",text:"Contact"},
        {id:"10",text:"I agree to the terms and conditions."},
        {id:"11",text:"Register"},
        {id:"12",text:"Loading"},
        {id:"13",text:"The email was sent"},
        {id:"14",text:"We have sent the login information to the address"},
        {id:"15",text:"Check your inbox or spam folder."},
        {id:"16",text:"Login"},
        {id:"17",text:"← Return to registration"},
        {id:"18",text:"You may already have an account."},
        {id:"19",text:"Failed to complete registration."},
        {id:"20",text:"Connection error. Try again later."},
        {id:"21",text:"Sending..."},
        {id:"22",text:"Forgot your password?"},
        {id:"23",text:"Login"},
        {id:"24",text:"Already have an account?"},
        {id:"25",text:"Go to login"},
        {id:"26",text:"The email was sent!"},
        {id:"27",text:"Check your mailbox."},
        {id:"28",text:"The link is valid for 30 minutes."},
        {id:"29",text:"← Back to registration"},
        {id:"30",text:"Registration could not be completed."},
        {id:"31",text:"You may already have an account."},
        {id:"32",text:"Sending..."},
        {id:"33",text:"Forgot your password?"},
        {id:"34",text:""},
        {id:"35",text:""},
        {id:"36",text:""},
    ],
    about:[
        {id:"0",text:"Find your dream space"},
        {id:"1",text:"Discover listings tailored for you"},
        {id:"2",text:"We are a Ukrainian company that offers a full range of services for searching and offering all types of real estate. At My Dream House, we connect you with your ideal property in City, Ukraine.\n" +
                "Our platform offers a wide range of listings for sale or rent, ensuring you find the perfect match\n" +
                "for your lifestyle and needs. Whether you're searching for a cozy apartment or a spacious family home,\n" +
                "our user-friendly interface makes the process simple and efficient. Trust us to help you navigate the\n" +
                "real estate market and unlock the door to your dreams."},
        {id:"3",text:"Learn more"},
        {id:"4",text:""},
        {id:"5",text:""},
        {id:"6",text:""},
    ],
    services:[
        {id:"0",text:"What you can do with our app"},
        {id:"1",text:"Free and premium features for owners, tenants and realtors"},
        {id:"2",text:"Free Services"},
        {id:"3",text:"Place Your Ads for Free"},
        {id:"4",text:"Post personal listings to sell or rent apartments, houses, or commercial properties at no cost."},
        {id:"5",text:"Find Properties for Free"},
        {id:"6",text:"Search and explore listings for purchase or rent without any fees."},
        {id:"7",text:"Premium Services"},
        {id:"8",text:"Main Page Video & Text Banner"},
        {id:"9",text:"Advertise your property or service via a featured video and a running text banner on the main page."},
        {id:"10",text:"Instant Email Alerts"},
        {id:"11",text:"Get notified by email immediately when a new listing matches your saved search parameters."},
        {id:"12",text:"Personal Realtor Promotion"},
        {id:"13",text:"Promote your realtor profile to users who prefer professional assistance in buying, selling, or renting properties."},
        {id:"14",text:"Subscribe to Premium Services"},
        {id:"15",text:"Premium services available with a subscription."},
        {id:"16",text:"Download a standard tenant-landlord agreement."},
        {id:"17",text:"Enter into a tenant agreement with the landlord yourself."},
        {id:"18",text:"Estimate the value of the property based on your description"},
        {id:"19",text:"Get a real estate or rental cost estimate using artificial intelligence"},
        {id:"20",text:"Promotion of your listing by the best real estate experts"},
        {id:"21",text:" Advertise your listing with professional photography and expert description from our top realtors."},
        {id:"22",text:""},
        {id:"23",text:""},
        {id:"24",text:""},
    ],  
    registrationErrors: {
        registeredWithPassword: "This email is registered with password. Please login using your password.",
        registeredWithGoogle: "This email is registered with Google. Redirecting to login...",
        incorrectPassword: "This email is already registered. Redirecting to login...",
        existingAccount: "Account already exists. Please log in.",
        allFieldsRequired: "All fields are required.",
        registrationFailed: "Failed to register. Please try again.",
        connectionError: "Connection error. Please try again later.",
        googleLoginFailed: "Google login failed. Please try again.",
        googleAuthFailed: "Google authentication failed.",
        successMessage: "Registration successful!",
    },
    loginErrors: {
        wrongPassword: "Invalid email or password.",
        loginFailed: "Login error. Please try again.",
        connectionError: "Connection error. Please try again later.",
        googleEmailWithPassword: "This email is registered with a password. Please sign in using the form above.",
        googleEmailWithGoogle: "This email is registered via Google. Please use the button below to sign in.",
        googleEmailWithMethod: "This email is registered via",
        googleLoginFailed: "Google login failed. Please try again.",
        googleAuthFailed: "Google authentication failed.",
    },
    advertisingVideo: {
        title: "Advertising Video Manager",
        labelDescription: "Ad description",
        placeholderDescription: "Enter ad description",
        labelOwner: "Owner's name",
        placeholderOwner: "Enter owner's name",
        videoReady: "Video ready to save",
        saving: "Saving…",
        save: "Save",
        savedVideos: "Saved Videos",
        noVideos: "No videos saved yet.",
        ownerPrefix: "Owner:",
        editPrefix: "Edit:",
        saveChanges: "Save changes",
        displayOnHome: "Display on Home page",
        delete: "Delete",
        successUpload: "The video was uploaded successfully.",
        failedSave: "Failed to save the ad. Please try again.",
        successFeatured: "The ad is now posted on the Home page!",
        enterDescription: "Please enter a new ad description before saving.",
        successUpdated: "Ad description updated successfully!",
        successPrefix: "Success:",
        failedDelete: "Failed to delete ad:",
        failedFeatured: "Failed to set featured:",
        failedUpdate: "Failed to update:",
    },
    promotionYourListing: {
        heroEyebrow: "Premium promotion",
        heroHeadline: "Your property deserves the best",
        heroSubtitle: "Professional photography, 3D video tour and expert description — everything you need to stand out among thousands.",
        heroCta: "Submit a request",
        heroScroll: "Explore services",
        service1Title: "Professional Photography",
        service1Desc: "Our photographers capture every angle in the best light. Quality photos triple the number of listing views.",
        service2Title: "3D Video Tour",
        service2Desc: "Immerse potential buyers in the space before the first visit. A panoramic video tour with a full property overview.",
        service3Title: "Expert Description",
        service3Desc: "Our realtors will craft a compelling text that highlights the advantages and speeds up the deal.",
        galleryTitle: "See the difference",
        gallerySubtitle: "Examples of our work — from ordinary to premium",
        formTitle: "Submit a request",
        formSubtitle: "We will contact you within 24 hours",
        labelName: "Your name",
        placeholderName: "John Smith",
        labelEmail: "Email address",
        placeholderEmail: "name@example.com",
        labelPhone: "Phone number",
        placeholderPhone: "+1 (___) ___-____",
        submitBtn: "Send request",
        submitting: "Sending…",
        successMsg: "Thank you! We will contact you shortly.",
        errorMsg: "Something went wrong. Please try again.",
        requiredMsg: "Please fill in all fields.",
        stat1Value: "3×",
        stat1Label: "more views",
        stat2Value: "98%",
        stat2Label: "satisfied clients",
        stat3Value: "24h",
        stat3Label: "to go live",
    },
    agreement:[
        {id:"0",text:"Standard agreement between tenant and landlord."},
        {id:"1",text:"Print the downloaded contract on A4 paper in two copies." +
                " Fill in the blanks with the necessary information, one for the tenant and the other for the landlord." +
                " Exchange contracts so that yours is filled in with the handwriting of your counterparty (the other party to the agreement)"},
        {id:"2",text:"Download Agreement"},
        {id:"3",text:""},
        {id:"4",text:""},
        {id:"5",text:""},
    ],
    footer:[
        {id:"0",text:"", href:"mailto:dimMryi@gmail.com?subject=Hello&body=I%20want%20to%20contact%20you"},
        {id:"1",text:"", href:"http://www.instagram.com/dimMryi"},
        {id:"2",text:"", href:""},
        {id:"3",text:"", href:"http://www.tiktok.com/@dimMryi"},
        {id:"4",text:"Our Contacts in social networks:", href:""},
        {id:"5",text:"Address: Svobody Square, 7, 61022, Kharkiv", href:"https://www.google.com.ua/maps/@50.0065439,36.2316092,15.56z?entry=ttu"},
        {id:"6",text:"", href:""},
        {id:"7",text:"Kharkiv Realtors unity", href:""},
        {id:"8",text:"", href:""},
        {id:"9",text:"© 2024-", href:""},
        {id:"10",text:" Real estate agency My Dream House", href:""},
        {id:"11", text:"",href:"http://t.me/"},
        {id:"12", text:"",href:"https://mail.google.com/mail/?view=cm&fs=1&to=dimMryi@gmail.com&su=Hello"},
    ],
    estimator:[
        {id:"0",text:"Please describe the property"},
        {id:"1",text:"There was an error rating the property. Please try again."},
        {id:"2",text:"AI-powered real estate estimator"},
        {id:"3",text:"Describe the property to get an approximate value"},
        {id:"4",text:"Example: 3-room apartment in the center of Poltava, 75 sq.m., European-quality renovation, 9th floor of 12, near a shopping center and park..."},
        {id:"5",text:"I'm counting on..."},
        {id:"6",text:"Calculate the cost"},
        {id:"7",text:"Clear"},
        {id:"8",text:"Evaluation result:"},
        {id:"9",text:"Rating history:"},
        {id:"10",text:"Object:"},
        {id:"11",text:"Estimate:"},
    ],
    links:[
        {id:"0",text:""},
        {id:"1",text:""},
        {id:"2",text:""},
        {id:"3",text:""},
        {id:"4",text:""},
        {id:"5",text:""},
        {id:"6",text:""},
        {id:"7",text:""},
        {id:"8",text:""},
        {id:"9",text:""},
        {id:"10",text:""},
    ],
    subscriptionToServices: {
        pageTitle: "Subscribe to Premium Services",
        pageSubtitle: "Choose the plan that best fits your needs",
        popular: "Most Popular",
        monthly: "/ mo",
        ctaBtn: "Pay Now",
        guarantee: "7-day money-back guarantee",
        securePayment: "Secure payment via LiqPay",
        cancelAnytime: "Cancel anytime",

        standardName: "Standard",
        standardPrice: "299",
        standardDesc: "Perfect for private owners who want to post listings and find the right property",
        std1: "Up to 5 active listings",
        std2: "Photo gallery up to 10 photos",
        std3: "1 active email notification search",
        std4: "Basic listing visibility priority",
        std5: "Access to agent contacts",

        premiumName: "Premium",
        premiumPrice: "599",
        premiumDesc: "For realtors and active sellers who need maximum reach and promotion",
        prem1: "Unlimited listings",
        prem2: "Photo gallery up to 30 photos",
        prem3: "Video banner on the homepage",
        prem4: "Unlimited email notification searches",
        prem5: "Top position in search results",
        prem6: "Agent profile on the platform",
        prem7: "AI property estimator (unlimited)",
        prem8: "Priority support 24/7",

        faqTitle: "Frequently Asked Questions",
        faq1Q: "When does the subscription become active?",
        faq1A: "Immediately after payment confirmation. You will receive a confirmation email.",
        faq2Q: "Can I cancel the subscription?",
        faq2A: "Yes, anytime in your profile settings with no penalties.",
        faq3Q: "Is there a free trial period?",
        faq3A: "First 7 days are free for new platform users.",
    },
    pagination: {
        prev: "← Prev",
        next: "Next →",
        pageOf: "Page {current} of {total}",
    },
    chat: {
        title: "Messages",
        chatTitle: "Chat with owner",
        noMessages: "No messages yet",
        startConversation: "Send the first message",
        placeholder: "Write a message...",
        back: "Back",
    },
    forgotPassword: {
        title: "Forgot password?",
        subtitle: "Enter your account email — we'll send you a password reset link.",
        submitBtn: "Send reset link",
        sendingBtn: "Sending...",
        backToLogin: "Back to sign in",
        sentTitle: "Check your inbox",
        sentText: "If an account with that address exists, we sent reset instructions to",
        sentHint: "The link is valid for 30 minutes. Check your Spam folder too.",
        errorEmpty: "Please enter your email.",
        connectionError: "Connection error. Please try again later.",
        serverError: "Server error. Please try again later.",
        leftHeadline: "Secure your account",
        leftSubtext: "We'll send a secure password reset link to your inbox.",
        statEncryption: "Encryption",
        statLinkExpiry: "Link validity",
        statSupport: "Support",
    },
    resetPassword: {
        validatingTitle: "Validating link...",
        invalidTitle: "Link is invalid",
        invalidText: "This password reset link has already been used or has expired (30 minutes). Please request a new one.",
        requestNewBtn: "Request new link",
        backToLogin: "← Back to sign in",
        successTitle: "Password changed!",
        successText: "Your password has been successfully updated. We will redirect you to the sign-in page...",
        successRedirectMsg: "Password changed successfully. You can now sign in.",
        formTitle: "New password",
        formSubtitle: "Enter a new password for your account. Minimum 8 characters.",
        newPasswordLabel: "New password",
        confirmPasswordLabel: "Confirm password",
        newPasswordPlaceholder: "Minimum 8 characters",
        saveBtn: "Save new password",
        savingBtn: "Saving...",
        showPassword: "Show password",
        hidePassword: "Hide password",
        passwordTooShort: "Password must be at least 8 characters.",
        passwordsMismatch: "Passwords do not match.",
        connectionError: "Connection error. Please try again later.",
        serverError: "Server error. Please try again later.",
        leftHeadline: "A fresh start",
        leftSubtext: "Set a strong password to protect your account.",
        statMinChars: "Min characters",
        statLinkExpiry: "Link validity",
        statEncryption: "Encryption",
    },
}
